services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=root
      - DB_NAME=expenseTracker
      - DB_PASSWORD=password
      - DB_DIALECT=mysql
    depends_on:
      - db
    volumes:
     - .:/app
     - /app/node_modules

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expenseTracker
    volumes:
      - expense-tracker_db_data:/var/lib/mysql

volumes:
  expense-tracker_db_data:
